version: '3.0'

services:
  rasa:
    build:
      context: .
      dockerfile: rasa-setup/Dockerfile
    container_name: rasa
    networks: ['rasa-network']
    ports:
    - "5005:5005"
    volumes:
    - "./rasa-app-data/:/app/"
    command: ["run","-m models", "--enable-api", "--cors", "*", "--endpoints", "endpoints.yml"]
    user: root
    depends_on:
      - action_server


  action_server:
    container_name: action_server
    image: rasa/rasa-sdk:latest
    networks: ['rasa-network']
    ports:
    - "5055:5055"
    volumes:
    - "./rasa-app-data/actions:/app/actions"
  duckling:
    container_name: duckling
    image: rasa/duckling:latest
    networks: ['rasa-network']
    ports:
    - "8000:8000"

  rasa_train:
    container_name: rasa_train
    build:
      context: .
      dockerfile: rasa-setup/Dockerfile
    networks: ['rasa-network']
    volumes:
      - "./rasa-app-data:/app"
    command: "train"
    depends_on:
      - "rasa"

# vào bằng http
  chatbot-ui:
    container_name: chatbot-ui
    build:
      context: .
      dockerfile: Chat-UI/Dockerfile
    networks: ['rasa-network']
    ports:
      - "5010:80"
    environment:
      - URL_CHATBOT=http://192.168.3.96:5005/
    depends_on:
      - "rasa"

networks: {rasa-network: {driver: bridge}}
#docker-compose --env-file .env.dev up -d
