version: '3.0'

services:
  rasa-dev:
    build:
      context: .
      dockerfile: rasa-setup/Dockerfile
    container_name: rasa-dev
    networks: ['rasa-network-dev']
    ports:
    - "5105:5005"
    volumes:
    - "./rasa-app-data/:/app/"
    command: ["run","-m models", "--enable-api", "--cors", "*", "--endpoints", "endpoints.yml"]
    user: root
    depends_on:
      - action_server-dev


  action_server-dev:
    container_name: action_server-dev
    image: rasa/rasa-sdk:latest
    networks: ['rasa-network-dev']
    ports:
    - "5155:5055"
    volumes:
    - "./rasa-app-data/actions:/app/actions"
  duckling-dev:
    container_name: duckling-dev
    image: rasa/duckling:latest
    networks: ['rasa-network-dev']
    ports:
    - "8100:8000"

  rasa_train-dev:
    container_name: rasa_train-dev
    build:
      context: .
      dockerfile: rasa-setup/Dockerfile
    networks: ['rasa-network-dev']
    volumes:
      - "./rasa-app-data:/app"
    command: "train"
    depends_on:
      - "rasa-dev"

# vào bằng http
  chatbot-ui-dev:
    container_name: chatbot-ui-dev
    build:
      context: .
      dockerfile: Chat-UI/Dockerfile
    networks: ['rasa-network-dev']
    ports:
      - "5010:80"
    environment:
      - URL_CHATBOT=http://192.168.3.96:5105/
    depends_on:
      - "rasa-dev"

networks: {rasa-network-dev: {driver: bridge}}
#docker-compose --env-file .env.dev up -d
