recipe: default.v1
assistant_id: form_bot
language: en

pipeline:
- name: LexicalSyntacticFeaturizer
- name: CountVectorsFeaturizer
  token_pattern: (?u)\b\w+\b
- name: DucklingEntityExtractor
  url: http://duckling:8000
  dimensions:
  - number
- name: DIETClassifier
  epochs: 200
  run_eagerly: True
- name: SpacyNLP
  model: en_core_web_sm
- name: SpacyTokenizer
- name: SpacyFeaturizer
- name: RegexFeaturizer
  analyzer: "char_wb"
  min_ngram: 1
  max_ngram: 4
- name: DIETClassifier
  epochs: 200
- name: EntitySynonymMapper
- name: ResponseSelector
# - name: "rasa.shared.nlu.training_data.formats.openai.transformers_tokenizer.OpenAIAutoTokenizer"
#   model_name: "vinai/phobert-base"

policies:
- name: TEDPolicy
  epochs: 100
- name: AugmentedMemoizationPolicy
- name: RulePolicy
cors:
  enabled: true
  allow_origins:
  - "*"
  allow_credentials: false
  allow_methods:
  - "OPTIONS"
  - "GET"
  - "POST"
  allow_headers:
  - "*"
